services:
  redis:
    image: redis:7
    container_name: etl-redis
    networks:
      - etl-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl-network

  etls:
    build: ./etls
    image: etls:latest
    networks:
      - etl-network

  frontend:
    build: ./frontend
    container_name: etl-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - etl-network
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: etl-backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - ./etls:/etls
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ETL_HOST_PATH=${ETL_HOST_PATH}
      - ETL_DOCKER_NETWORK=etl-manager_default
    depends_on:
      - redis
      - postgres
    networks:
      - etl-network

  worker:
    build: ./backend
    command: sh -c "celery -A config worker -l info --concurrency=5 --prefetch-multiplier=1 -Ofair --max-tasks-per-child=50"
    volumes:
      - ./backend:/app
      - ./etls:/etls
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ETL_HOST_PATH=${ETL_HOST_PATH}
      - ETL_DOCKER_NETWORK=etl-manager_default
      - CELERY_WORKER_CONCURRENCY=5
      - ETL_CONTAINER_MEM_LIMIT=512m
      - ETL_CONTAINER_CPUSET=
    depends_on:
      - redis
      - postgres
    networks:
      - etl-network




volumes:
  postgres_data:
  frontend_node_modules:

networks:
  etl-network:
    name: etl-manager_default
    driver: bridge
