services:
  redis:
    image: redis:7
    container_name: etl-redis
    networks:
      - etl-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl-network

  etls:
    build: ./etls
    image: etls:latest
    networks:
      - etl-network

  frontend:
    image: node:20-alpine
    container_name: etl-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    networks:
      - etl-network
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: etl-backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - ./etls:/etls
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ETL_PATH=${ETL_PATH}
    depends_on:
      - redis
      - postgres
    networks:
      - etl-network

  worker:
    build: ./backend
    container_name: etl-worker
    command: celery -A config worker -l info
    volumes:
      - ./backend:/app
      - ./etls:/etls
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ETL_PATH=${ETL_PATH}
    depends_on:
      - redis
      - postgres
    networks:
      - etl-network




volumes:
  postgres_data:

networks:
  etl-network:
    driver: bridge