# Generated by Django 6.0.2 on 2026-02-09 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'ETL Ativa'), ('2', 'ETL Inativa'), ('3', 'ETL com Erro')], default='1', max_length=1)),
                ('coowners', models.ManyToManyField(blank=True, related_name='etl_coowned', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etl_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
