# Generated by Django 6.0.2 on 2026-02-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etl',
            name='rota',
            field=models.CharField(choices=[('1', 'caminho/pasta1'), ('2', 'caminho/pasta2'), ('3', 'caminho/pasta3')], default='1', max_length=1),
        ),
    ]
